### ISSUE TITLE
Does this depend on ember-cli-fastboot?

### ISSUE THREAD

**Issue by samselikoff** [embermap/ember-cli-fastboot-testing#20]
Believe it does, if so we should add somehow to `package.json`

**Comment by ryanto** [comment]
Should this be a peerDependency?

**Comment by samselikoff** [comment]
Good question, just asked again here: https://discuss.emberjs.com/t/best-practices-for-including-3rd-party-libraries-in-an-addon/15200/6

**Comment by ryanto** [comment]
I think we should follow prember's lead here, since prember also uses `ember-cli-fastboot` in Ember's package.json `ember-addon` config: https://github.com/ef4/prember/blob/master/package.json#L72

It looks like they give setup instructions that say to install `ember-cli-fastboot`: https://github.com/ef4/prember#quick-start

And then if the plugin fails to build they show this error: https://github.com/ef4/prember/blob/df566f26d6f2c869c9e42bbbc117a817018384c3/lib/prerender.js#L52

We don't have a broccoli plugin, so I'm not sure where to put that try/catch, but it's probably something we should explore.

**Comment by samselikoff** [comment]
Makes sense, I like having some declaration of the dependency and this is the next best thing to `package.json`.

I'd say put the `pkg` check in the `included()` hook:

```js
  included() {
    this._super.included.apply(this, arguments);

    // new code
  }
```

[ECTailwind](https://github.com/embermap/ember-cli-tailwind/blob/master/index.js#L35) for reference

**Comment by ryanto** [comment]
Fixed in https://github.com/embermap/ember-cli-fastboot-testing/pull/38
